name: Main

on:
  "workflow_dispatch":
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Build for Linux x86_64
        run: bun build --target bun-linux-x64 --compile packages/cli/index.ts --outfile telecraft-linux-x86_64
      - name: Build for Linux aarch64
        run: bun build --target bun-linux-arm64 --compile packages/cli/index.ts --outfile telecraft-linux-aarch64
      - name: Build for Windows x86_64
        run: bun build --target bun-windows-x64 --compile packages/cli/index.ts --outfile telecraft-windows-x86_64.exe
      - name: Build for MacOS aarch64
        run: bun build --target bun-darwin-arm64 --compile packages/cli/index.ts --outfile telecraft-macos-aarch64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: telecraft-*
