name: Main

on:
  "workflow_dispatch":
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build for Linux
        run: deno compile --target x86_64-unknown-linux-gnu -A --unstable-kv --output telecraft-linux-x86_64 packages/cli/index.ts
      - name: Build for Windows
        run: deno compile --target x86_64-pc-windows-msvc -A --unstable-kv --output telecraft-win-x86_64.exe packages/cli/index.ts
      - name: Build for MacOS
        run: deno compile --target aarch64-apple-darwin -A --unstable-kv --output telecraft-macos-aarch64 packages/cli/index.ts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: telecraft
